### ISSUE TITLE
usql package

### ISSUE THREAD

**Issue by kenshaw** [flipee/pkgbuilds#4]
Hi, I'm Ken Shaw, the original author of [`usql`](https://github.com/xo/usql). We have a number of developers on our team that are Arch users, and would like to do automated releases for `usql` and ensure the `usql` package here is sync'd with its release cycle. 

If possible, please email me -- kenshaw@gmail.com -- so we can coordinate. 

Thanks in advance, and appreciate the massive effort put into these package builds!

**Comment by flipee** [comment]
Added as a co-maintainer. Thanks!
